signalfx/opentelemetry-ibm-mq-monitoring

pom.xml

During build, pull com.ibm.mq.allclient.jar under /target for easier local run and test.
do not redistribute jar to customers though.

com.ibm.mq.allclient.jar /target

---

.github/workflows/build.yaml
README.md
pom.xml
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollectorTest.java

otel java components have standardized around junit5 with mockito and assertj. This aligns with that and makes the tests actually pass.

Make the tests run and modernize the stack.

---

pom.xml
src/main/java/com/appdynamics/extensions/webspheremq/WMQMonitorTask.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQStatusCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireTStatusCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsPublisher.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsPublisherJob.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ResetQStatsCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollector.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricAssert.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricPropertiesAssert.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsPublisherJobTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollectorTest.java

This primarily expands the data/test coverage in the ChannelMetricsCollector (now 100%). The previous loop left a lot uncovered. 
This also extracts the `Runnable` nature from the collector in favor of having a separate job class that does that work.

More test cleanup/enhancement

---

src/main/java/com/appdynamics/extensions/opentelemetry/MQOtelTranslator.java
src/main/java/com/appdynamics/extensions/webspheremq/WMQMonitorTask.java
src/main/java/com/appdynamics/extensions/webspheremq/common/Constants.java
src/main/java/com/appdynamics/extensions/webspheremq/config/QueueManager.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ReadConfigurationEventQueueCollector.java
src/main/resources/conf/config.yml

Rebasing https://github.com/signalfx/opentelemetry-ibm-mq-monitoring/pull/24 off latest main.

Add the ability to read queue manager configuration from configuration events

---

src/main/java/com/appdynamics/extensions/webspheremq/WMQMonitorTask.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireChannelCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQStatusCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQueueManagerCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireTStatusCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricCreator.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ResetQStatsCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollector.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireChannelCmdCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollectorTest.java

This new class is responsible for creating the metric. By factoring it out of the MetricCollector base class, we continue to decouple the child implementations from the parent. This also helps to modularize and shrink responsibilities.

Factor out new class called MetricCreator.

---

src/main/java/com/appdynamics/extensions/webspheremq/WMQMonitorTask.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricCreator.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollector.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireChannelCmdCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollectorTest.java

There was no need for MetricCreator to have the entire `MonitorContextConfiguration` when it just needs the prefix. This simplifies it and fixes the main build.

Simplify MetricCreator by using true dependency

---

src/main/java/com/appdynamics/extensions/webspheremq/WMQContext.java
src/main/java/com/appdynamics/extensions/webspheremq/WMQMonitorTask.java
src/main/java/com/appdynamics/extensions/webspheremq/config/QueueManager.java

simplify instantiation of the queue manager, inlining its creation.
Move the encryptionkey out of the QueueManager configuration since it is global.

Tidy code around QueueManager connection instantiation

---

src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireChannelCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQStatusCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQueueManagerCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireTStatusCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ResetQStatsCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollector.java

This is the last method in the `MetricsCollector` parent that was called by child implementations. Removing that is this next step in breaking apart this parent/child dependency.

Decouple implementations from parent via getMetricsToReport().

---

src/main/java/com/appdynamics/extensions/webspheremq/WMQMonitorTask.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/IntAttributesBuilder.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsCollectorContext.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollectorTest.java

This introduces a new bundle/data class called `MetricsCollectorContext` that is a stand-in for the original behavior that was all baked into the parent class `MetricsCollector`. This demonstrates how we can finally free these *Collector classes from the oppression of their ancestry, starting with the `ChannelMetricsCollector`.
Rather than doing all of them at once and making a review nightmare, I just establish the pattern here so that it can be repeated across the remaining collector classes.

Finally free the ChannelMetricsCollector

---

pom.xml

- remove obsolete copy <fileset dir="src/main/resources/conf" include……s="monitor.xml,config.yml"/>
Before remove, I got the following error during build: 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  41.116 s
[INFO] Finished at: 2025-04-30T00:36:38-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.0.0:run (install) on project ibm-mq-monitoring-extension: An Ant BuildException has occured: /Users/matho/appdynamics/signalfx/opentelemetry-ibm-mq-monitoring/src/main/resources/conf does not exist.
[ERROR] around Ant part …

Remove obsolete copy <fileset dir="src/main/resources/conf"

---

src/main/java/com/appdynamics/extensions/webspheremq/WMQMonitorTask.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireChannelCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireTStatusCmdCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/IntAttributesBuilder.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/JobSubmitterContext.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricCreator.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsCollectorContext.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollector.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollector.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricPropertiesAssert.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollectorTest.java
src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollectorTest.java

This one includes refactoring of:
* `QueueManagerMetricsCollector`
* `TopicMetricsCollector`...which is responsible for creating and scheduling...
* `InquireTStatusCmdCollector`
There's a new class called `JobSubmitterContext` in order to help those classes that are `MetricsPublisher` implementations that also schedule delegate `MetricsPublisherJobs` via the executor service. This isn't yet used by the QueueMetricsCollector but soon will be.

Migrate several other implementations away from MetricsCollector ancestry

---

src/main/java/com/appdynamics/extensions/webspheremq/common/WMQUtil.java
src/main/java/com/appdynamics/extensions/webspheremq/config/WMQMetricOverride.java
src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricCreator.java

The thought of mutating a config class that is carried around for the lifecycle of the app is a bit terrifying. This cleans it up some and makes it easier to reason about and not accidentally modify.

Make config classes immutable

---

src/test/java/com/splunk/ibm/mq/metricscollector/QueueCollectionBuddyTest.java

My IDE just won't abide by having different compilation levels between 11 and 8. This fixes the issue for me.

use Arrays.asList to avoid compilation issues

---

src/integrationTest/java/com/splunk/ibm/mq/integration/tests/JakartaPutGet.java
src/integrationTest/java/com/splunk/ibm/mq/integration/tests/WMQMonitorIntegrationTest.java
src/integrationTest/resources/conf/test-config.yml
src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
src/main/java/com/splunk/ibm/mq/common/Constants.java
src/main/java/com/splunk/ibm/mq/common/WMQUtil.java
src/main/java/com/splunk/ibm/mq/config/QueueManager.java
src/main/java/com/splunk/ibm/mq/metricscollector/PerformanceEventQueueCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/ReadConfigurationEventQueueCollector.java
src/main/java/com/splunk/ibm/mq/opentelemetry/Main.java
src/main/java/com/splunk/ibm/mq/opentelemetry/OpenTelemetryMetricWriteHelper.java

This PR adds a new class of metric collection, specifically to capture performance metrics exposed by system queues when queue manager performance events are enabled and the queue limits are set.
The events are made available in a system queue and we can consume them and report them as cumulative counters.

Add performance events reader

---

src/integrationTest/java/com/splunk/ibm/mq/integration/tests/JakartaPutGet.java
src/integrationTest/java/com/splunk/ibm/mq/integration/tests/WMQMonitorIntegrationTest.java
src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
src/main/java/com/splunk/ibm/mq/config/QueueManager.java
src/main/java/com/splunk/ibm/mq/metricscollector/QueueManagerEventCollector.java

This PR builds on top of #79 and adds a new collector for queue manager events, specifically unauthorized events. The events are reported with the attribute of the user name and the name of the application.

Authority events

---

src/integrationTest/java/com/splunk/ibm/mq/integration/tests/JakartaPutGet.java
src/integrationTest/java/com/splunk/ibm/mq/integration/tests/WMQMonitorIntegrationTest.java
src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
src/main/java/com/splunk/ibm/mq/metricscollector/ChannelMetricsCollector.java
src/main/java/com/splunk/ibm/mq/opentelemetry/MQOtelTranslator.java

This showed a bug in WMQMonitorTask: our countdown latch is initialized with a smaller number than the number of jobs we submit.

Count more states as active

---

src/integrationTest/java/com/splunk/ibm/mq/integration/tests/TestWMQMonitor.java
src/integrationTest/java/com/splunk/ibm/mq/integration/tests/WMQMonitorIntegrationTest.java
src/main/java/com/splunk/ibm/mq/WMQMonitor.java
src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
src/main/java/com/splunk/ibm/mq/opentelemetry/Main.java

Phase 1 -- in which `WMQMonitorTask` no longer inherits from `AMonitorTaskRunnable ` but is instead just a meager `Runnable` that can be submitted to a humble `ExecutorService`.
Up next - freeing `WMQMonitor` from `ABaseMonitor`.

Decouple from appd tasks

---

pom.xml
src/integrationTest/java/com/splunk/ibm/mq/integration/tests/TestWMQMonitor.java
src/integrationTest/java/com/splunk/ibm/mq/integration/tests/WMQMonitorIntegrationTest.java
src/main/java/com/splunk/ibm/mq/TaskJob.java
src/main/java/com/splunk/ibm/mq/WMQMonitor.java
src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
src/main/java/com/splunk/ibm/mq/metricscollector/JobSubmitterContext.java
src/main/java/com/splunk/ibm/mq/metricscollector/ReadConfigurationEventQueueCollector.java
src/main/java/com/splunk/ibm/mq/opentelemetry/ConfigWrapper.java
src/main/java/com/splunk/ibm/mq/opentelemetry/Main.java
src/test/java/com/splunk/ibm/mq/metricscollector/ChannelMetricsCollectorTest.java
src/test/java/com/splunk/ibm/mq/metricscollector/TopicMetricsCollectorTest.java

This removes a bunch of the machinery dependency on the appd job/task/worker sluge, in favor of just using some thread pools (ExecutorService, ThreadPoolExecutors). In many cases, we're able to leverage the `ConfigWrapper` with a few changes to clean up some things and reduce the direct yaml dependency as well.

Decouple from appd job/worker/whatever machinery.

---

src/main/java/com/splunk/ibm/mq/config/ExcludeFilters.java
src/main/java/com/splunk/ibm/mq/metricscollector/ChannelMetricsCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/InquireChannelCmdCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/InquireQueueManagerCmdCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/InquireTStatusCmdCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/ListenerMetricsCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/MessageBuddy.java
src/main/java/com/splunk/ibm/mq/metricscollector/MessageFilter.java
src/main/java/com/splunk/ibm/mq/metricscollector/MetricsCollectorContext.java
src/main/java/com/splunk/ibm/mq/metricscollector/PerformanceEventQueueCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/QueueCollectionBuddy.java
src/main/java/com/splunk/ibm/mq/metricscollector/QueueManagerEventCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/QueueManagerMetricsCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/QueueMetricsCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/ReadConfigurationEventQueueCollector.java

A continued modernization effort. A bunch of the collector classes have this exclude filter logic sprinkled inside these deep loops with conditionals and exceptions, which made for poor readability. This refactors that into a new `MessageFilter` class that can be used more consistently and helps to do pre-filtering of messages, instead of considering each one at a time.
The results is tighter loops with less indention.

Filter cleanups

---

src/main/java/com/splunk/ibm/mq/opentelemetry/ConfigWrapper.java

The default is so small it will create a thread pool exhaustion before any jobs are set.

bump up default thread pool count to 20

---

golden/otelconf.yaml
src/integrationTest/java/com/splunk/ibm/mq/integration/tests/TestWMQMonitor.java
src/integrationTest/java/com/splunk/ibm/mq/integration/tests/WMQMonitorIntegrationTest.java
src/main/java/com/splunk/ibm/mq/WMQMonitor.java
src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
src/main/java/com/splunk/ibm/mq/metricscollector/PerformanceEventQueueCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/QueueManagerEventCollector.java
src/main/java/com/splunk/ibm/mq/opentelemetry/Config.java
src/main/java/com/splunk/ibm/mq/opentelemetry/MQOtelTranslator.java
src/main/java/com/splunk/ibm/mq/opentelemetry/Main.java
src/main/java/com/splunk/ibm/mq/opentelemetry/OpenTelemetryMetricWriteHelper.java

This is a meaningful change as it tests that we can export metrics using the metrics provider rather than translating them.
The changes:
* no more multiple resources. No resource for now.
* a heartbeat gauge is created and passed to all queue manager tasks.
* the exporter default aggregation is now set to send last value of a metric.
* Important: we now send metrics explicitly at the end of each cycle. This way both metrics that are coming from the translation and the metrics reported by gauges are in the same export.
* We no longer tap in the thread pool of tasks to export. Exporting is so important, it might be best to give it its own thread pool. For now, we use the default threadpool, which uses daemon threads - not sure yet if we want to override that.

use a gauge to capture heartbeat metrics

---

src/main/java/com/splunk/ibm/mq/opentelemetry/ConfigWrapper.java
src/test/java/com/splunk/ibm/mq/opentelemetry/ConfigWrapperTest.java

make sure we don't underallocate threads, so we don't starve the pool and block execution

Ensure we have a minimum set of threads

---

pom.xml
src/main/java/com/splunk/ibm/mq/WMQContext.java
src/main/java/com/splunk/ibm/mq/WMQMonitor.java
src/main/java/com/splunk/ibm/mq/config/ExcludeFilters.java
src/main/java/com/splunk/ibm/mq/metricscollector/ChannelMetricsCollector.java
src/main/java/com/splunk/ibm/mq/metricscollector/QueueMetricsCollector.java
src/main/java/com/splunk/ibm/mq/opentelemetry/Config.java
src/main/java/com/splunk/ibm/mq/util/WMQUtil.java
src/test/java/com/splunk/ibm/mq/metricscollector/ChannelMetricsCollectorTest.java
src/test/java/com/splunk/ibm/mq/metricscollector/InquireChannelCmdCollectorTest.java
src/test/java/com/splunk/ibm/mq/metricscollector/QueueManagerMetricsCollectorTest.java
src/test/java/com/splunk/ibm/mq/metricscollector/TopicMetricsCollectorTest.java
src/test/resources/log4j.xml

This was being used just to source a couple of transitive dependencies, including snakeyaml, jackson, and guava. The guava usages were minimal, so I just replaced those with standard java calls. We depend on snakeyaml and jackson explicitly now.

Remove dependency on appd-exts-commons
