signalfx/opentelemetry-ibm-mq-monitoring

- src/main/java/com/appdynamics/extensions/opentelemetry/Config.java
- src/main/java/com/appdynamics/extensions/opentelemetry/MQOtelTranslator.java
- src/main/java/com/appdynamics/extensions/opentelemetry/Main.java
- src/main/java/com/appdynamics/extensions/webspheremq/WMQContext.java
- src/main/java/com/appdynamics/extensions/webspheremq/common/Constants.java
- src/main/java/com/appdynamics/extensions/webspheremq/common/WMQUtil.java
- src/main/java/com/appdynamics/extensions/webspheremq/config/QueueManager.java
- src/main/java/com/appdynamics/extensions/webspheremq/config/WMQMetricOverride.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQStatusCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireTStatusCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsCollector.java
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollectorTest.java
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollectorTest.java
- reformat code for readability
- refactor code and extra copy-and-paste code into reusable method
- fix Sonarqube code improvement suggestions
- when necesary, added if(logger.isDebugEnabled());  especially involving expensive operations
> reformat code and fix code analysis suggestion

- src/main/java/com/appdynamics/extensions/opentelemetry/MQOtelTranslator.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollector.java
- src/main/resources/conf/config.yml
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollectorTest.java
Add support for queue type attribute, as well as capturing MQIA_Q_SERVICE_INTERVAL and MQIA_Q_SERVICE_INTERVAL_EVENT
> Add queue type and couple critical metrics

- src/main/java/com/appdynamics/extensions/opentelemetry/MQOtelTranslator.java
Fix the translation of mq manager status to mq.manager.status to avoid clashing with channel status
> Fix translation

- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireTStatusCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsCollectorContext.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollector.java
This is the next in line to get updated. More to follow....
> Free InquireTStatusCmdCollector from the ancestry

- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireChannelCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQStatusCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQueueManagerCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireTStatusCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsPublisher.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsPublisherJob.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueMetricsCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ReadConfigurationEventQueueCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/ResetQStatsCmdCollector.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollector.java
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ChannelMetricsCollectorTest.java
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireChannelCmdCollectorTest.java
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/ListenerMetricsCollectorTest.java
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/MetricsPublisherJobTest.java
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueCollectionBuddyTest.java
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/QueueManagerMetricsCollectorTest.java
- src/test/java/com/appdynamics/extensions/webspheremq/metricscollector/TopicMetricsCollectorTest.java
Removing this exception helps remove a dependency of the code to the machine agent code base.
> Remove TaskExecutionException

- .github/workflows/integration-test.yml
- src/test/resources/conf/config.yml
- update github workflow with permission on mq objects
> Set MQ permission for integration test workflow

- src/main/java/com/appdynamics/extensions/webspheremq/WMQMonitorTask.java
- src/main/java/com/appdynamics/extensions/webspheremq/metricscollector/InquireQCmdCollector.java
- made extractAndReportMetrics() easier to understand and more maintainable.
> Refactor wmqmonitor task

- src/main/java/com/splunk/ibm/mq/WMQMonitor.java
- make initializeMoreStuff() more readable
> Refactor WMQMontior initialize method

- src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
> Refactor WMQMonitorTask run

- .github/workflows/integration-test.yml
- run-mq/README.md
- src/integrationTest/resources/conf/test-config.yml
- src/integrationTest/resources/conf/test-queuemgr-config.yml
fix the connection to the queue using the dev queue used for admins in the docker image
> fix integration test auth

- src/integrationTest/java/com/splunk/ibm/mq/integration/tests/WMQMonitorIntegrationTest.java
- src/main/java/com/splunk/ibm/mq/WMQMonitor.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/Config.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/ConfigWrapper.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/Main.java
* Test was throwing warnings due to wrong import, fix that
* Abstract out some config concerns that muddy up the Main class.
> Cleanup Main and warnings

- src/main/java/com/splunk/ibm/mq/opentelemetry/ConfigWrapper.java
- src/test/java/com/splunk/ibm/mq/opentelemetry/ConfigWrapperTest.java
- src/test/resources/conf/config.yml
Add tests and fix a bug in ConfigWrapper.
> fix configwrapper

- src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
- src/main/java/com/splunk/ibm/mq/metricscollector/JobSubmitterContext.java
- src/main/java/com/splunk/ibm/mq/metricscollector/MetricsPublisher.java
- src/main/java/com/splunk/ibm/mq/metricscollector/MetricsPublisherJob.java
- src/main/java/com/splunk/ibm/mq/metricscollector/QueueMetricsCollector.java
- src/main/java/com/splunk/ibm/mq/metricscollector/TopicMetricsCollector.java
- src/test/java/com/splunk/ibm/mq/metricscollector/TopicMetricsCollectorTest.java
Refactor handling of jobs to create the countdown latch after capturing all jobs.
> Refactor countdown latch

- src/test/java/com/splunk/ibm/mq/metricscollector/ChannelMetricsCollectorTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/InquireChannelCmdCollectorTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/ListenerMetricsCollectorTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/QueueCollectionBuddyTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/QueueManagerMetricsCollectorTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/TopicMetricsCollectorTest.java
Continuing to chip away at the dependency...
> Clean up tests still using the old appd classes

- src/main/java/com/splunk/ibm/mq/TaskJob.java
- src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
- src/main/java/com/splunk/ibm/mq/metricscollector/PerformanceEventQueueCollector.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/MQOtelTranslator.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/Main.java
Also delete a very noisy log for translations.
> add more debug logs

- README.md
- config.yml
- golden/config.yml
- src/integrationTest/java/com/splunk/ibm/mq/integration/tests/JakartaPutGet.java
- src/integrationTest/java/com/splunk/ibm/mq/integration/tests/WMQMonitorIntegrationTest.java
- src/integrationTest/resources/conf/test-config.yml
- src/main/java/com/splunk/ibm/mq/WMQContext.java
- src/main/java/com/splunk/ibm/mq/WMQMonitor.java
- src/main/java/com/splunk/ibm/mq/WMQMonitorTask.java
- src/main/java/com/splunk/ibm/mq/config/QueueManager.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/ConfigWrapper.java
- src/test/resources/conf/config.yml
This feature is not used and encrypts the password in place.
> remove support of encrypted password

- src/main/java/com/splunk/ibm/mq/WMQMonitor.java
- src/main/java/com/splunk/ibm/mq/config/QueueManager.java
Make YAML parsing able to ignore unknown fields, and log loudly any errors related to setting up queue managers
> YAML parsing management

- src/main/java/com/splunk/ibm/mq/metricscollector/Metric.java
- src/main/java/com/splunk/ibm/mq/metricscollector/MetricCreator.java
- src/main/java/com/splunk/ibm/mq/metricscollector/QueueManagerMetricsCollector.java
- src/main/java/com/splunk/ibm/mq/metricscollector/Transformer.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/MQOtelTranslator.java
- src/test/java/com/splunk/ibm/mq/metricscollector/QueueManagerMetricsCollectorTest.java
Trying to create the attributes and names and bypass the translation layer.
> Refactor to directly create OpenTelemetry metrics

- golden/docker-compose.yaml
- src/main/java/com/splunk/ibm/mq/WMQMonitor.java
- src/main/java/com/splunk/ibm/mq/metrics/MetricsConfig.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/Config.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/ConfigWrapper.java
- src/main/java/com/splunk/ibm/mq/opentelemetry/Main.java
- src/test/java/com/splunk/ibm/mq/metricscollector/ChannelMetricsCollectorTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/InquireChannelCmdCollectorTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/ListenerMetricsCollectorTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/QueueCollectionBuddyTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/QueueManagerMetricsCollectorTest.java
- src/test/java/com/splunk/ibm/mq/metricscollector/TopicMetricsCollectorTest.java
- src/test/java/com/splunk/ibm/mq/opentelemetry/ConfigTest.java
- templates/registry/java/MetricsConfig.java.j2
This was yielding some unfriendly warnings and just needed some cleanup.
> clean up deprecated method usage

- src/main/java/com/splunk/ibm/mq/metrics/Metrics.java
- src/main/java/com/splunk/ibm/mq/metrics/MetricsConfig.java
- templates/registry/java/Metrics.java.j2
- templates/registry/java/MetricsConfig.java.j2
Some things that errorprone was pointing out when porting over to java contrib.
> Improve generated class templates
